#!/usr/bin/env bash
# install.sh - install deployment helper to a system prefix (default /opt/deployment)
# 
# This installer:
#  - accepts --prefix and --repo
#  - creates the repo directory under PREFIX/REPO_NAME
#  - installs deployment.sh (if present) to PREFIX/deployment.sh
#  - writes a deploy.conf.sh file (if none exists) populated with known defaults
#  - creates an excludes.txt (if none exists)
#
# All comments and code are written in English.
set -euo pipefail

DEFAULT_PREFIX="/opt/deployment"
PREFIX="${DEPLOYMENT_PREFIX:-${DEFAULT_PREFIX}}"   # environment var can override default, CLI --prefix wins later
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=0
REPO_NAME="example"

usage() {
  cat <<USAGE
Usage: install.sh [--prefix DIR] [--repo NAME] [--dry-run] [--help]
  --prefix DIR        Install prefix (default: ${DEFAULT_PREFIX}; can be overridden with DEPLOYMENT_PREFIX env)
  --repo NAME         Name of repo directory to create (default: example)
  --dry-run           Show actions without modifying the system
  -h, --help          Show this help
USAGE
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2;;
    --repo) REPO_NAME="$2"; shift 2;;
    --dry-run) DRY_RUN=1; shift;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

info() { printf '%s\n' "$*"; }
err()  { printf '%s\n' "$*" >&2; }

# Normalize PREFIX (remove trailing slash)
PREFIX="${PREFIX%/}"

install_file() {
  local src="$1" dest="$2"
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: install $src -> $dest"
  else
    mkdir -p "$(dirname "$dest")"
    cp -a "$src" "$dest"
    chmod 0755 "$dest"
  fi
}

info "Installing to prefix: $PREFIX (repo: ${REPO_NAME})"
if [[ $DRY_RUN -eq 1 ]]; then
  info "DRY RUN mode enabled"
fi

# Basic sanity checks
if [[ -z "$PREFIX" || "$PREFIX" == "/" ]]; then
  err "Refusing to install to empty or root (/) prefix. Set --prefix or DEPLOYMENT_PREFIX to a valid directory."
  exit 2
fi

# Install main script if present
if [[ -f "${SRC_DIR}/deployment.sh" ]]; then
  install_file "${SRC_DIR}/deployment.sh" "${PREFIX}/deployment.sh"
else
  info "Note: deployment.sh not found in source dir; please copy it manually if needed."
fi

# Prepare repo dir under PREFIX/<repo-name>
REPO_DIR="${PREFIX}/${REPO_NAME}"
if [[ $DRY_RUN -eq 1 ]]; then
  info "DRY RUN: mkdir -p ${REPO_DIR}"
else
  mkdir -p "${REPO_DIR}"
fi

# Install example deploy.conf.sh from source if present to repo as ".example"
if [[ -f "${SRC_DIR}/deploy.conf.sh.example" ]]; then
  install_file "${SRC_DIR}/deploy.conf.sh.example" "${REPO_DIR}/deploy.conf.sh.example"
fi

# Create a real configuration file with known data (only if it doesn't already exist)
DEPLOY_CONF="${REPO_DIR}/deploy.conf.sh"
if [[ -f "${DEPLOY_CONF}" ]]; then
  info "Config already exists: ${DEPLOY_CONF} (not overwriting)"
else
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: would create config ${DEPLOY_CONF} with values derived from:"
    info "  PREFIX=${PREFIX}"
    info "  REPO_NAME=${REPO_NAME}"
    info "  REPO_DIR=${REPO_DIR}"
    info "  DEPLOY_SCRIPT=${PREFIX}/deployment.sh"
  else
    cat > "${DEPLOY_CONF}" <<EOF
#!/usr/bin/env bash
#
# deploy.conf.sh - Generated by install.sh for REPO_NAME='${REPO_NAME}'
# Edit values if needed. This file is sourced by deployment.sh and must not contain secrets.
#
# All variables are documented in deployment/deployment.sh and override its defaults.
#

# Git repository URL (SSH recommended, set to your repository)
# Example for the 'adventor' project:
# REPO_URL="git@github.com:noviceiii/adventor.git"
REPO_URL=""

# Branch to deploy
BRANCH="main"

# Destination directory (live production path).
# Default uses a sensible path pattern; adjust to your environment.
DEST_DIR="/var/www/www.t9t.ch/${REPO_NAME}"

# Parent directory used for temporary clones (must be writable by the deploy user)
TMP_PARENT="${REPO_DIR}/tmp"

# Where backups will be stored
BACKUP_DIR="${REPO_DIR}/backup"

# Number of backups to keep (older backups are pruned)
KEEP_BACKUPS=5

# Optional rsync excludes file (relative to repo root or absolute path)
EXCLUDES_FILE="${REPO_DIR}/excludes.txt"

# File/Directory ownership to set on deployed files
OWNER="www-data"
GROUP="www-data"

# Default permissions for directories and files (octal strings)
DIR_MODE="0755"
FILE_MODE="0644"

# Special modes to apply to specific files after deploy.
# Format: "relative/path:owner:group:mode"
# Example entries for the adventor project:
SPECIAL_MODES=(
  # "subscribers.db:www-data:www-data:0660"
  # "config.php:www-data:www-data:0640"
)

# Git clone depth (1 = shallow)
GIT_DEPTH=1

# Dry run default (0 = real deploy, 1 = dry run)
DRY_RUN=0

EOF
    chmod 0644 "${DEPLOY_CONF}"
    info "Created config: ${DEPLOY_CONF}"
  fi
fi

# Create excludes.txt with sensible defaults (if not present)
EXCLUDES_FILE="${REPO_DIR}/excludes.txt"
if [[ -f "${EXCLUDES_FILE}" ]]; then
  info "Excludes file already exists: ${EXCLUDES_FILE} (not overwriting)"
else
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: would create excludes file ${EXCLUDES_FILE} with default patterns"
  else
    cat > "${EXCLUDES_FILE}" <<EOF
# excludes.txt - files and directories to ignore during deployment operations
.git
.gitignore
tmp/
backup/
node_modules/
*.log
.DS_Store
EOF
    chmod 0644 "${EXCLUDES_FILE}"
    info "Created excludes: ${EXCLUDES_FILE}"
  fi
fi

# Create tmp/ and backup/ skeletons for convenience
for d in tmp backup; do
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: mkdir -p ${REPO_DIR}/${d}"
  else
    mkdir -p "${REPO_DIR}/${d}"
  fi
done

info "Install complete. Edit ${DEPLOY_CONF} and ${EXCLUDES_FILE} to match your project."
