#!/usr/bin/env bash
# install.sh - install deployment helper to a system prefix (default /opt/deployment)
set -euo pipefail

DEFAULT_PREFIX="/opt/deployment"
PREFIX="${DEFAULT_PREFIX}"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=0
REPO_NAME="example"

usage() {
  cat <<USAGE
Usage: install.sh [--prefix DIR] [--repo NAME] [--dry-run] [--help]
  --prefix DIR        Install prefix (default: ${DEFAULT_PREFIX})
  --repo NAME         Name of repo directory to create (default: example)
  --dry-run           Show what would be done, do not modify system
USAGE
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2;;
    --repo) REPO_NAME="$2"; shift 2;;
    --dry-run) DRY_RUN=1; shift;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

info() { printf '%s\n' "$*"; }
err() { printf '%s\n' "$*" >&2; }

# Normalize PREFIX (remove trailing slash)
PREFIX="${PREFIX%/}"

install_file() {
  local src="$1" dest="$2"
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: install $src -> $dest"
  else
    mkdir -p "$(dirname "$dest")"
    cp -a "$src" "$dest"
    chmod 0755 "$dest"
  fi
}

info "Installing to prefix: $PREFIX (repo: ${REPO_NAME})"
if [[ $DRY_RUN -eq 1 ]]; then
  info "DRY RUN mode enabled"
fi

# Basic sanity checks
if [[ "$PREFIX" == "" || "$PREFIX" == "/" ]]; then
  err "Refusing to install to empty or root (/) prefix. Set --prefix to a valid directory."
  exit 2
fi

# Install main script if present
if [[ -f "${SRC_DIR}/deployment.sh" ]]; then
  install_file "${SRC_DIR}/deployment.sh" "${PREFIX}/deployment.sh"
else
  info "Note: deployment.sh not found in source dir; please copy it manually if needed."
fi

# Prepare repo dir under PREFIX/<repo-name>
REPO_DIR="${PREFIX}/${REPO_NAME}"
if [[ $DRY_RUN -eq 1 ]]; then
  info "DRY RUN: mkdir -p ${REPO_DIR}"
else
  mkdir -p "${REPO_DIR}"
fi

# Install example deploy.conf.sh if present in source
if [[ -f "${SRC_DIR}/deploy.conf.sh" ]]; then
  install_file "${SRC_DIR}/deploy.conf.sh" "${REPO_DIR}/deploy.conf.sh.example"
fi

# Create a real configuration file with known data (only if it doesn't already exist)
DEPLOY_CONF="${REPO_DIR}/deploy.conf.sh"
if [[ -f "${DEPLOY_CONF}" ]]; then
  info "Config already exists: ${DEPLOY_CONF} (not overwriting)"
else
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: would create config ${DEPLOY_CONF} with:"
    info "  PREFIX=${PREFIX}"
    info "  REPO_NAME=${REPO_NAME}"
    info "  REPO_DIR=${REPO_DIR}"
    info "  DEPLOY_SCRIPT=${PREFIX}/deployment.sh"
  else
    cat > "${DEPLOY_CONF}" <<EOF
# deploy.conf.sh - generated by install.sh
# Edit values as needed for your environment.

# Installation prefix used by the installer
PREFIX="${PREFIX}"

# Repository name and directory
REPO_NAME="${REPO_NAME}"
REPO_DIR="${REPO_DIR}"

# Path to the main deployment script (installed by this installer)
DEPLOY_SCRIPT="${PREFIX}/deployment.sh"

# Directories used by deployment operations
TMP_DIR="${REPO_DIR}/tmp"
BACKUP_DIR="${REPO_DIR}/backup"

# Add your repository URL or other deployment-specific settings below:
# REPO_URL=""
# DEPLOY_USER=""
# TARGET_HOST=""

EOF
    chmod 0644 "${DEPLOY_CONF}"
    info "Created config: ${DEPLOY_CONF}"
  fi
fi

# Create excludes.txt with sensible defaults (if not present)
EXCLUDES_FILE="${REPO_DIR}/excludes.txt"
if [[ -f "${EXCLUDES_FILE}" ]]; then
  info "Excludes file already exists: ${EXCLUDES_FILE} (not overwriting)"
else
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: would create excludes file ${EXCLUDES_FILE} with patterns:"
    info ".git"
    info ".gitignore"
    info "tmp/"
    info "backup/"
    info "node_modules/"
    info "*.log"
    info ".DS_Store"
  else
    cat > "${EXCLUDES_FILE}" <<EOF
# excludes.txt - files and directories to ignore during deployment operations
.git
.gitignore
tmp/
backup/
node_modules/
*.log
.DS_Store
EOF
    chmod 0644 "${EXCLUDES_FILE}"
    info "Created excludes: ${EXCLUDES_FILE}"
  fi
fi

# Create tmp/ and backup/ skeletons for convenience
for d in tmp backup; do
  if [[ $DRY_RUN -eq 1 ]]; then
    info "DRY RUN: mkdir -p ${REPO_DIR}/${d}"
  else
    mkdir -p "${REPO_DIR}/${d}"
  fi
done

info "Install complete. Edit ${DEPLOY_CONF} and, if needed, ${REPO_DIR}/deploy.conf.sh.example. Create your repo dir under ${PREFIX}/<your-repo>."
